:: lifecycle: default
::     phase: validate
:: mvn org.codehaus.mojo:buildplan-maven-plugin:2.2.3-SNAPSHOT:list-phase@list-phase-on-validate;
:: mvn org.codehaus.mojo:buildplan-maven-plugin:2.2.3-SNAPSHOT:list-phase@list-phase-on-validate-2;
::     phase: initialize
::     phase: generate-sources
::     phase: process-sources
::     phase: generate-resources
::     phase: process-resources
@echo on
call mvn org.apache.maven.plugins:maven-resources-plugin:2.6:resources@default-resources
@echo on
@echo phase: compile
call mvn org.apache.maven.plugins:maven-compiler-plugin:3.1:compile@default-compile
::     phase: process-classes
::     phase: generate-test-sources
::     phase: process-test-sources
::     phase: generate-test-resources
::     phase: process-test-resources
:: mvn org.apache.maven.plugins:maven-resources-plugin:2.6:testResources@default-testResources;
::     phase: test-compile
:: mvn org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile@default-testCompile;
::     phase: process-test-classes
::     phase: test
:: mvn org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test@default-test;
::     phase: prepare-package
::     phase: package
:: mvn org.apache.maven.plugins:maven-jar-plugin:2.4:jar@default-jar;
:: mvn org.apache.maven.plugins:maven-dependency-plugin:3.6.0:copy@copy;
::     phase: pre-integration-test
::     phase: integration-test
::     phase: post-integration-test
::     phase: verify
:: mvn org.codehaus.mojo:buildplan-maven-plugin:2.2.3-SNAPSHOT:list-phase@list-phase-on-verify;
::     phase: install
:: mvn org.apache.maven.plugins:maven-install-plugin:2.5.1:install@default-install;
:: mvn org.apache.maven.plugins:maven-install-plugin:2.5.1:install-file@install-snapshot;
::     phase: deploy
:: mvn org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy@default-deploy;